# Numpy Basic 

### Logo k likhy howy code jo hum use krty hy apni asani k liy

- How to install numpy

>* pip install numpy 
* write in terminal on VScode

- How to use
  

In [2]:
import numpy as np

## Vector
- Vector is a single dimension array
# Matrics 
- its a two demintion aray

## Three d.Array
- tensor

In [4]:
b = np.zeros(2)
b

array([0., 0.])

In [5]:
b= np.ones(4)
b

array([1., 1., 1., 1.])

In [7]:
d = np.empty(3)
d

array([1.24955698e-311, 0.00000000e+000, 6.47591605e-319])

In [8]:
a =np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [9]:
a =np.arange(2,6)
a

array([2, 3, 4, 5])

In [10]:
a =np.arange(2,15,2)
a

array([ 2,  4,  6,  8, 10, 12, 14])

In [11]:
a =np.linspace(2,10,num=5)
a

array([ 2.,  4.,  6.,  8., 10.])

## Numpy practice

### Creating numpy Array

In [13]:
food= np.array(["Pakora","Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [14]:
type(food)

numpy.ndarray

In [15]:
food[1]

'Samosa'

In [16]:
len(food)

3

In [17]:
# spacify your data type

a=np.ones(50,dtype=np.int64)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

# Function of Array

In [18]:
a= np.array([2,4,5,6,2.4])
a

array([2. , 4. , 5. , 6. , 2.4])

In [20]:
a.sort()
a

array([2. , 2.4, 4. , 5. , 6. ])

In [21]:
# Concatinate
b = np.array([4,5,6,5,4,3,2,2,3,4])
b

array([4, 5, 6, 5, 4, 3, 2, 2, 3, 4])

In [23]:
c=np.concatenate((a,b))
c

array([2. , 2.4, 4. , 5. , 6. , 4. , 5. , 6. , 5. , 4. , 3. , 2. , 2. ,
       3. , 4. ])

In [25]:
c.sort()
c

array([2. , 2. , 2. , 2.4, 3. , 3. , 4. , 4. , 4. , 4. , 5. , 5. , 5. ,
       6. , 6. ])

# 2-D Array 

In [26]:
x=np.array([[1,3],[2,4]])
x

array([[1, 3],
       [2, 4]])

In [28]:
y=np.array([[5,6],[8,7]])
y

array([[5, 6],
       [8, 7]])

In [30]:
c = np.concatenate((x,y), axis=0)
c

array([[1, 3],
       [2, 4],
       [5, 6],
       [8, 7]])

In [31]:
c.ndim

2

In [32]:
c.size

8

In [33]:
c.shape

(4, 2)

In [35]:
# reshap array
a= np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
# 1 into 2 dimensional array
x=np.array([1,2,3,4,5,6,7,8,9])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x.shape

(9,)

In [40]:
# Row Vise array
y=  a[np.newaxis,:]
y

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [41]:
y.shape

(1, 9)

In [42]:
# Coloum vise array
y = a[:,np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [43]:
y.sum()

36

In [44]:
y*4

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24],
       [28],
       [32]])

In [45]:
y.min()

0

In [46]:
y.max()

8

In [47]:
y.sum()

36